const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.ScriptsInEvents.Efase1_Event3_Act4,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Fixar: 0},
	{Animação: 0},
	{Chave: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Sprite: 0},
	{espinhos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sprite4: 0},
	{Texto: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{ação: 0},
	{Piscar: 0},
	{Inimigo1: 0},
	{Marcador: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{PlanoDeFundoEmBlocos10: 0},
	{PlanoDeFundoEmBlocos11: 0},
	{Texto2: 0},
	{PlanoDeFundoEmBlocos12: 0},
	{caixa: 0},
	{PlanoDeFundoEmBlocos14: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos13: 0},
	{Sprite7: 0},
	{Inimigo: 0},
	{Inimigo2: 0},
	{PlanoDeFundoEmBlocos16: 0},
	{sim: 0},
	{no: 0},
	{menu: 0},
	{start: 0},
	{Âncora: 0},
	{Vida: 0},
	{porta: 0},
	{Áudio: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite8: 0},
	{Bau: 0},
	{Item_chave: 0},
	{preto: 0},
	{Personagem_texto: 0},
	{FonteDeSprites: 0},
	{PlanoDeFundoEmBlocos15: 0},
	{Fim: 0},
	{PlanoDeFundoEmBlocos17: 0},
	{Next: 0},
	{hist: 0},
	{PlanoDeFundoEmBlocos18: 0},
	{Texto3: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Animação: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Inimigo1: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos10: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos11: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos12: class extends self.ITiledBackgroundInstance {},
	caixa: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos14: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos13: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos16: class extends self.ITiledBackgroundInstance {},
	sim: class extends self.ITextInstance {},
	no: class extends self.ITextInstance {},
	menu: class extends self.ITiledBackgroundInstance {},
	start: class extends self.ISpriteInstance {},
	Vida: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Item_chave: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	preto: class extends self.ISpriteInstance {},
	Personagem_texto: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos15: class extends self.ITiledBackgroundInstance {},
	Fim: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos17: class extends self.ITiledBackgroundInstance {},
	Next: class extends self.ITextInstance {},
	hist: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos18: class extends self.ITiledBackgroundInstance {},
	Texto3: class extends self.ITextInstance {}
}